version: '3'
services:
  web:
    image: eu.gcr.io/eshop-trzos/eshop-email-sender-{ENVIRONMENT}:{COMMIT_SHA}
    volumes:
      - .:/eshop-email-sender
    entrypoint:
      - /bin/sh
      - ./kubernetes/test-script.sh
    ports:
      - "3000:3000"
